# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtWidgets

from help import Help
from result import Result
from src.prediction import Prediction


class Page(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(333, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 80, 101, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sex = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sex.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.sex.setObjectName("sex")
        self.verticalLayout.addWidget(self.sex)
        self.age = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.age.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.age.setObjectName("age")
        self.verticalLayout.addWidget(self.age)
        self.cp = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cp.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.cp.setObjectName("cp")
        self.verticalLayout.addWidget(self.cp)
        self.trestbps = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.trestbps.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.trestbps.setObjectName("trestbps")
        self.verticalLayout.addWidget(self.trestbps)
        self.chol = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.chol.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.chol.setObjectName("chol")
        self.verticalLayout.addWidget(self.chol)
        self.fbs = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fbs.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.fbs.setObjectName("fbs")
        self.verticalLayout.addWidget(self.fbs)
        self.restecg = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.restecg.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.restecg.setObjectName("restecg")
        self.verticalLayout.addWidget(self.restecg)
        self.thalach = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.thalach.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.thalach.setObjectName("thalach")
        self.verticalLayout.addWidget(self.thalach)
        self.exang = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.exang.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.exang.setObjectName("exang")
        self.verticalLayout.addWidget(self.exang)
        self.oldpeak = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.oldpeak.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.oldpeak.setObjectName("oldpeak")
        self.verticalLayout.addWidget(self.oldpeak)
        self.slope = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.slope.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}"
        )
        self.slope.setObjectName("slope")
        self.verticalLayout.addWidget(self.slope)
        self.ca = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ca.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.ca.setObjectName("ca")
        self.verticalLayout.addWidget(self.ca)
        self.thal = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.thal.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.thal.setObjectName("thal")
        self.verticalLayout.addWidget(self.thal)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 80, 131, 371))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sex_select = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.sex_select.setObjectName("sex_select")
        self.sex_select.addItem("")
        self.sex_select.addItem("")
        self.verticalLayout_2.addWidget(self.sex_select)
        self.age_select = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.age_select.setObjectName("age_select")
        self.verticalLayout_2.addWidget(self.age_select)
        self.cp_select = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.cp_select.setMaximum(3)
        self.cp_select.setObjectName("cp_select")
        self.verticalLayout_2.addWidget(self.cp_select)
        self.trestbps_select = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.trestbps_select.setMinimum(90)
        self.trestbps_select.setMaximum(200)
        self.trestbps_select.setObjectName("trestbps_select")
        self.verticalLayout_2.addWidget(self.trestbps_select)
        self.chol_select = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.chol_select.setMinimum(100)
        self.chol_select.setMaximum(600)
        self.chol_select.setObjectName("chol_select")
        self.verticalLayout_2.addWidget(self.chol_select)
        self.fbs_select = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.fbs_select.setObjectName("fbs_select")
        self.fbs_select.addItem("")
        self.fbs_select.addItem("")
        self.verticalLayout_2.addWidget(self.fbs_select)
        self.restecg_select = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.restecg_select.setMaximum(2)
        self.restecg_select.setObjectName("restecg_select")
        self.verticalLayout_2.addWidget(self.restecg_select)
        self.thalach_select = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.thalach_select.setMinimum(70)
        self.thalach_select.setMaximum(220)
        self.thalach_select.setObjectName("thalach_select")
        self.verticalLayout_2.addWidget(self.thalach_select)
        self.exang_select = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.exang_select.setObjectName("exang_select")
        self.exang_select.addItem("")
        self.exang_select.addItem("")
        self.verticalLayout_2.addWidget(self.exang_select)
        self.lodpeak_select = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.lodpeak_select.setMaximum(6.2)
        self.lodpeak_select.setObjectName("lodpeak_select")
        self.verticalLayout_2.addWidget(self.lodpeak_select)
        self.slope_select = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.slope_select.setObjectName("slope_select")
        self.slope_select.addItem("")
        self.slope_select.addItem("")
        self.slope_select.addItem("")
        self.verticalLayout_2.addWidget(self.slope_select)
        self.ca_select = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.ca_select.setMaxVisibleItems(3)
        self.ca_select.setObjectName("ca_select")
        self.ca_select.addItem("")
        self.ca_select.addItem("")
        self.ca_select.addItem("")
        self.ca_select.addItem("")
        self.verticalLayout_2.addWidget(self.ca_select)
        self.thal_select = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.thal_select.setMaxVisibleItems(3)
        self.thal_select.setObjectName("thal_select")
        self.thal_select.addItem("")
        self.thal_select.addItem("")
        self.thal_select.addItem("")
        self.thal_select.addItem("")
        self.verticalLayout_2.addWidget(self.thal_select)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 30, 151, 31))
        self.label.setStyleSheet(
            "QLabel {\n"
            "    color: #333; /* 文本颜色 */\n"
            "    font-size: 18px; /* 字体大小 */\n"
            "}\n"
            ""
        )
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 460, 231, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.help = QtWidgets.QPushButton(
            self.horizontalLayoutWidget, clicked=lambda: self.open_help_window()
        )
        self.help.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #4CAF50; /* 背景颜色 */\n"
            "    border: none; /* 去掉边框 */\n"
            "    color: white; /* 文本颜色 */\n"
            "    padding: 10px 20px; /* 内边距 */\n"
            "    font-size: 16px; /* 字体大小 */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #45a049; /* 鼠标悬停时的背景颜色 */\n"
            "}\n"
            ""
        )
        self.help.setObjectName("help")
        self.horizontalLayout.addWidget(self.help)
        self.button_next_page = QtWidgets.QPushButton(
            self.horizontalLayoutWidget, clicked=lambda: self.open_result_window()
        )
        self.button_next_page.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #4CAF50; /* 背景颜色 */\n"
            "    border: none; /* 去掉边框 */\n"
            "    color: white; /* 文本颜色 */\n"
            "    padding: 10px 20px; /* 内边距 */\n"
            "    font-size: 16px; /* 字体大小 */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #45a049; /* 鼠标悬停时的背景颜色 */\n"
            "}\n"
            ""
        )
        self.button_next_page.setObjectName("button_next_page")
        self.horizontalLayout.addWidget(self.button_next_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sex.setText(_translate("MainWindow", "sex："))
        self.age.setText(_translate("MainWindow", "age："))
        self.cp.setText(_translate("MainWindow", "cp："))
        self.trestbps.setText(_translate("MainWindow", "trestbps："))
        self.chol.setText(_translate("MainWindow", "chol："))
        self.fbs.setText(_translate("MainWindow", "fbs："))
        self.restecg.setText(_translate("MainWindow", "restecg："))
        self.thalach.setText(_translate("MainWindow", "thalach："))
        self.exang.setText(_translate("MainWindow", "exang："))
        self.oldpeak.setText(_translate("MainWindow", "oldpeak："))
        self.slope.setText(_translate("MainWindow", "slope："))
        self.ca.setText(_translate("MainWindow", "ca:"))
        self.thal.setText(_translate("MainWindow", "thal:"))
        self.sex_select.setItemText(0, _translate("MainWindow", "男"))
        self.sex_select.setItemText(1, _translate("MainWindow", "女"))
        self.fbs_select.setItemText(0, _translate("MainWindow", "高于120 mg/dL"))
        self.fbs_select.setItemText(1, _translate("MainWindow", "低于120 mg/dL"))
        self.exang_select.setItemText(0, _translate("MainWindow", "是"))
        self.exang_select.setItemText(1, _translate("MainWindow", "否"))
        self.slope_select.setItemText(0, _translate("MainWindow", "0"))
        self.slope_select.setItemText(1, _translate("MainWindow", "1"))
        self.slope_select.setItemText(2, _translate("MainWindow", "2"))
        self.ca_select.setItemText(0, _translate("MainWindow", "0"))
        self.ca_select.setItemText(1, _translate("MainWindow", "1"))
        self.ca_select.setItemText(2, _translate("MainWindow", "2"))
        self.ca_select.setItemText(3, _translate("MainWindow", "3"))
        self.thal_select.setItemText(0, _translate("MainWindow", "0"))
        self.thal_select.setItemText(1, _translate("MainWindow", "1"))
        self.thal_select.setItemText(2, _translate("MainWindow", "2"))
        self.thal_select.setItemText(3, _translate("MainWindow", "3"))
        self.label.setText(_translate("MainWindow", "心脏病预测小程序"))
        self.help.setText(_translate("MainWindow", "帮助"))
        self.button_next_page.setText(_translate("MainWindow", "预测"))

    def open_help_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Help()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_result_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Result()
        self.ui.setupUi(self.window)
        if self.predict() > 0.5:
            self.ui.predictDisplay.setText("患有心脏病")
        else:
            self.ui.predictDisplay.setText("未患有心脏病")
        self.window.show()

    def get_data(self):
        age = self.age_select.value()
        sex = 1 if self.sex_select.currentText() == "男" else 0
        cp = self.cp_select.value()
        trestbps = self.trestbps_select.value()
        chol = self.chol_select.value()
        fbs = 1 if self.fbs_select.currentText() == "高于120 mg/dL" else 0
        restecg = self.restecg_select.value()
        thalach = self.thalach_select.value()
        exang = 1 if self.exang_select.currentText() == "是" else 0
        oldpeak = self.lodpeak_select.value()
        slope = self.slope_select.currentText()
        ca = self.ca_select.currentText()
        thal = self.thal_select.currentText()
        # print(f"age = {age}, sex = {sex}, cp = {cp}, trestbps = {trestbps}, chol = {chol}, fbs = {fbs}, restecg = {restecg}, thalach = {thalach}, exang = {exang}, oldpeak = {oldpeak}, slope = {slope}, ca = {ca}, thal = {thal}")
        return (
            age,
            sex,
            cp,
            trestbps,
            chol,
            fbs,
            restecg,
            thalach,
            exang,
            oldpeak,
            slope,
            ca,
            thal,
        )

    def predict(self):
        (
            age,
            sex,
            cp,
            trestbps,
            chol,
            fbs,
            restecg,
            thalach,
            exang,
            oldpeak,
            slope,
            ca,
            thal,
        ) = self.get_data()
        predict = Prediction()
        data = [
            [
                age,
                sex,
                cp,
                trestbps,
                chol,
                fbs,
                restecg,
                thalach,
                exang,
                oldpeak,
                slope,
                ca,
                thal,
            ]
        ]
        outcome = predict.predict(data)
        return outcome


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Page()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
